name: Docs

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    name: Generate versioned docs site
    runs-on: ubuntu-18.04
    steps:
    - name: Cancel Previous Actions
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.3
      id: go
    - name: Install Protoc
      uses: solo-io/setup-protoc@master
      with:
        version: '3.6.1'
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Update deps
      run: |
        make install-go-tools
    - name: Gcloud Login
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@7159039b8c614f8ed6d9bd75af3f6113681a8ff4
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GC_FIREBASE_GHA_PROJECT_ID }}
        service_account_key: ${{ secrets.GC_FIREBASE_GHA_SA_JSON_KEY }}
        export_default_credentials: true

    - name: Generate versioned docs site
      env:
        RELEASE: true
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: make -C docs build-site
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.GC_FIREBASE_GHA_SA_JSON_KEY }}
        projectId: ${{ secrets.GC_FIREBASE_GHA_PROJECT_ID }}
        channelId: live
        entryPoint: ./docs/ci
